# Generated by Django 2.2.2 on 2019-06-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0004_auto_20190624_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexaskill',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vad.AlexaAuthor'),
        ),
        migrations.AlterField(
            model_name='alexaskill',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
