# Generated by Django 2.2.2 on 2019-06-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0007_auto_20190624_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexaskill',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vad.AlexaAuthor'),
        ),
        migrations.AlterField(
            model_name='alexaskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vad.AlexaCategory'),
        ),
    ]
