# Generated by Django 2.2.2 on 2019-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0009_auto_20190624_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexareview',
            name='found_helpful_count',
            field=models.IntegerField(null=True),
        ),
    ]
