# Generated by Django 2.2.2 on 2019-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0010_auto_20190624_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexareview',
            name='date',
            field=models.DateField(),
        ),
    ]
