# Generated by Django 2.2.2 on 2019-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0011_auto_20190624_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexareview',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
    ]
