# Generated by Django 2.2.2 on 2019-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0012_auto_20190624_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexareview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
