# Generated by Django 2.2.2 on 2019-06-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0016_auto_20190625_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleassistantaction',
            name='system_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
