# Generated by Django 2.2.2 on 2019-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0017_auto_20190625_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleassistantdevice',
            name='display_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='googleassistantdevice',
            name='image_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='googleassistantdevice',
            unique_together={('display_name', 'image_url')},
        ),
    ]
