# Generated by Django 2.2.2 on 2019-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0019_auto_20190625_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleassistantaction',
            name='icon_url',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googleassistantaction',
            name='image_url',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googleassistantaction',
            name='privacy_policy_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
