# Generated by Django 2.2.2 on 2019-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0020_auto_20190625_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleassistantreview',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleassistantreview',
            name='unique_id',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
