# Generated by Django 2.2.2 on 2019-06-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0021_auto_20190626_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexaskill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vad.AlexaCategory'),
        ),
    ]
