# Generated by Django 2.2.2 on 2019-06-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0022_auto_20190627_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAssistantAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.AddField(
            model_name='googleassistantaction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vad.GoogleAssistantAuthor'),
        ),
    ]
