# Generated by Django 2.2.2 on 2019-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0023_auto_20190629_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleassistantaction',
            name='system_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
