# Generated by Django 2.2.2 on 2019-06-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0024_auto_20190629_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleassistantauthor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='googleassistantauthor',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
