# Generated by Django 2.2.2 on 2019-07-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0025_auto_20190629_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexaskill',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vad.AlexaAuthor'),
        ),
    ]
