# Generated by Django 2.2.2 on 2019-08-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0026_auto_20190724_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='alexacategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vad.AlexaCategory'),
        ),
    ]
