# Generated by Django 2.2.2 on 2019-08-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0027_alexacategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alexareview',
            name='skill',
        ),
        migrations.AddField(
            model_name='alexaskill',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vad.AlexaReview'),
        ),
    ]
