# Generated by Django 2.2.2 on 2019-08-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0028_auto_20190826_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceapp',
            name='alexa_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vad.AlexaSkill'),
        ),
    ]
