# Generated by Django 2.2.2 on 2019-09-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0030_auto_20190829_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
        migrations.AddField(
            model_name='device',
            name='googleDevices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vad.GoogleAssistantDevice'),
        ),
        migrations.CreateModel(
            name='AlexaDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, unique=True)),
                ('image_url', models.URLField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('display_name', 'image_url')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='alexaDevices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vad.AlexaDevices'),
        ),
    ]
