# Generated by Django 2.2.2 on 2019-09-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0031_auto_20190910_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='alexaDevices',
        ),
        migrations.RemoveField(
            model_name='device',
            name='googleDevices',
        ),
    ]
