# Generated by Django 2.2.2 on 2019-09-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0032_auto_20190910_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlexaDevices',
            new_name='AlexaDevice',
        ),
    ]
