# Generated by Django 2.2.2 on 2019-09-11 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0034_auto_20190910_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
    ]
