# Generated by Django 2.2.2 on 2019-09-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0035_remove_device_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='alexaskill',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
