# Generated by Django 2.2.5 on 2019-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0036_alexaskill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alexaskill',
            name='added_elastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleassistantaction',
            name='added_elastic',
            field=models.BooleanField(default=False),
        ),
    ]
