# Generated by Django 2.2.5 on 2019-10-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vad', '0039_auto_20191003_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexaskill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vad.Category'),
        ),
    ]
